version: '3.8'
services:
  db:
    container_name: stats_db
    image: mysql:8.0
    environment:
      # DB_COLLATION: ${DB_COLLATION}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_PUBLIC_KEY_RETRIEVAL: "true" 
      MYSQL_SSL_MODE: "DISABLED"
    ports:
      - "3307:3306"
    # volumes:
    #   - ./db:/var/lib/mysql
    restart: always

  stats_api:
    build:
      context: ./stats_api/
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: $ ${DB_HOST}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    restart: always

  stats_web_ui_app: 
    build:
      context: ./stats_web_ui/docker/8.2/
      dockerfile: Dockerfile
    env_file:
      - ./stats_web_ui/.env
    volumes:
      - ./stats_web_ui:/var/www/html
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    depends_on:
      - db
      - stats_api
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    restart: always
