version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: lpas_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./db:/var/lib/mysql

  stats_api:
    build:
      context: ./stats_api/
      dockerfile: Dockerfile
    container_name: stats_api
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: $ ${DB_HOST}
      DB_NAME: ${DB_DATABASE}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"

  stats_web_ui_app: 
    build:
      context: ./stats_web_ui/docker/8.2/
      dockerfile: Dockerfile
    container_name: stats_web_ui_app
    env_file:
      - ./stats_web_ui/.env
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    restart: always
    depends_on:
      - db
      - stats_api
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
